### ISSUE TITLE
SvgStore adds excessive slash to svg sprite path

### ISSUE THREAD

**Issue by fr-ench** [mrsum/webpack-svgstore-plugin#61]
Sorry to write again. This time I noticed the bug with the path happening at this line of code: 
 _ajax.open('GET', baseUrl + '/' + url, true);

It means that if I use smth like this with webpack
_new SvgStore(
        path.resolve("svg/src/**/*.svg"),
        "/dist",
        {
                name: 'svg.sprite.svg',
                prefix: 'icon-',
                chunk: 'headscripts',
               baseUrl:  "/assets"
            }))_
then I'm getting svg.sprite.svg inside the dist folder and ajax request to the
_baseUrl + '/' + url = "/assets" + "/" + "/dist/svg.sprite.svg" = "/assets//dist/svg.sprite.svg"_
path.

In this case "/dist" might be a wrong option, of course (but how else can I put the sprite exactly to the dist folder anyway?). But if I use this code with webpack-dev-server with _publicPath="/assets/dist/"_ in my webpack config file and
_new SvgStore(
      path.resolve("svg/src/**/*.svg"),
      "",
      {
                name: 'svg.sprite.svg',
                prefix: 'icon-',
                chunk: 'headscripts',
                baseUrl: "http://localhost:8080"
            }_
then I'm getting this line of code in the resulting headscripts file:
_document.addEventListener('DOMContentLoaded', svgXHR('/assets/dist/svg-icons.sprite.svg', 'http://localhost:8080'), false);_

Which again leads us to 
_baseUrl + '/' + url = "http://localhost:8080" + "/" + "/assets/dist/svg-icons.sprite.svg" = "http://localhost:8080//assets/dist/svg-icons.sprite.svg"_

If I provide a baseUrl as an empty string in this case, then I'm getting a totally invialid path
_"//assets/dist/svg-icons.sprite.svg";_

Despite the fact that IIS handles paths with doube slash as normal path and files are avaliable to the ajax request, this is still a problem because it's not a consistent behaviour. 

I believe "/" should only be added for the cases when baseUrl is undefined, to avoid such confusion to happen with paths.

**Comment by lgordey** [comment]
Thank you for your feedback.
Fixed version will be released at the weekend I hope.

**Comment by fr-ench** [comment]
@lgordey, thank you!

**Comment by lgordey** [comment]
@fr-ench Please, try fixed plugin version from branch - https://github.com/lgordey/webpack-svgstore-plugin/tree/feature/fix-paths-bug

**Comment by fr-ench** [comment]
@lgordey,

For me it still doesn't look correct. 
This lines of code
_fullPath = 'http://' + (baseUrl + '/' + url)
    .replace(/^http\:\/\//, '')
    .replace(/\/+/g, '/')
    .replace(/\/+$/, '');

will product invalid url if baseUrl and publicPath are both undefined (baseUrl undefined) and url will start just with the domain name. The same problem happens if I define basicUrl that starts with "https://" because then I'll get https:/domain... 
Why would you remove "http:"?

**Comment by lgordey** [comment]
@fr-ench Hi!
Try 2.1.4 version

**Comment by lgordey** [comment]
@fr-ench Tell me please if the problem is still relevant.
